### ISSUE TITLE
Get the order invoice for the specific date

### ISSUE THREAD

**Issue by rddewan** [Genaker/laragento#2]
Hi there,
Is it possible to fetch the invoice detail for the specific date using laragento?

**Comment by Genaker** [comment]
Sure.

I’ve seen people doing it with *raw queries*, like this:

$q->where(DB::raw("DATE(created_at) = '".date('Y-m-d')."'"));

Or without raw queries by datetime, like this:

$q->where('created_at', '>=', date('Y-m-d').' 00:00:00'));

Luckily, Laravel Query Builder offers a more *Eloquent* solution:

$q->whereDate('created_at', '=', date('Y-m-d'));

Or, of course, instead of PHP *date()*you can use Carbon
<https://github.com/briannesbitt/Carbon>:

$q->whereDate('created_at', '=', Carbon::today()->toDateString());


There are three more useful functions to filter out dates:

$q->whereDay('created_at', '=', date('d'));
$q->whereMonth('created_at', '=', date('m'));
$q->whereYear('created_at', '=', date('Y'));

Isn’t it nice and easy?

The only thing is if you’re dealing with *timezones*, you should totally
use Carbon and make some more complex queries, but that’s a topic for a
whole another article.

**Comment by Genaker** [comment]
@rddewan Let me know if you have other questions.

**Comment by rddewan** [comment]
@Genaker thanks you for your response. i will come back to you once i the test is completed

**Comment by Genaker** [comment]
@rddewan Let me know if you have any questions...
